# Generated by Django 5.0.7 on 2024-07-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_price_item_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(default='https://imgs.search.brave.com/DPZzH5S4Yx7XboIZ_hAJtVWt_HAuIbeRX9zDQRzapYU/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly93d3cu/d2ViZnguY29tL3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDIzLzA4/LzkwX2hvd190b19p/bWFnZV9wbGFjZWhv/bGRlcnMtMTAyNHg0/NjIucG5n', max_length=500),
        ),
    ]
