# Generated by Django 5.0.7 on 2024-07-23 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='item_image',
        ),
    ]
